# Generated by Django 5.0.1 on 2025-10-17 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SummarizationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_text",
                    models.TextField(help_text="Original text to be summarized"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("extractive", "Extractive"),
                            ("abstractive", "Abstractive"),
                            ("hybrid", "Hybrid"),
                            ("keyword", "Keyword"),
                        ],
                        help_text="Summarization mode to use",
                        max_length=20,
                    ),
                ),
                (
                    "max_length",
                    models.IntegerField(
                        default=150, help_text="Maximum length of the summary in words"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the task",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when task was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when task was last updated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who submitted the task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summarization_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Summarization Task",
                "verbose_name_plural": "Summarization Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SummaryResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("output_text", models.TextField(help_text="Generated summary text")),
                (
                    "characters_processed",
                    models.IntegerField(
                        help_text="Number of characters processed from input"
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        help_text="Time taken to process in milliseconds"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        help_text="Associated summarization task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="summarizer.summarizationtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Summary Result",
                "verbose_name_plural": "Summary Results",
            },
        ),
        migrations.AddIndex(
            model_name="summarizationtask",
            index=models.Index(
                fields=["user", "status"], name="summarizer__user_id_97c21c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="summarizationtask",
            index=models.Index(
                fields=["status", "created_at"], name="summarizer__status_6ce914_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="summarizationtask",
            index=models.Index(
                fields=["created_at"], name="summarizer__created_9c39f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="summaryresult",
            index=models.Index(fields=["task"], name="summarizer__task_id_35c00e_idx"),
        ),
    ]
