# Generated by Django 5.0.1 on 2025-10-25 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountSecurityState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concurrent_session_cap",
                    models.IntegerField(
                        default=2,
                        help_text="Account-specific session limit (overrides Plan default)",
                    ),
                ),
                (
                    "is_temp_locked",
                    models.BooleanField(
                        default=False,
                        help_text="If True, block all API requests for this account",
                    ),
                ),
                (
                    "last_flag_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why account was flagged/locked",
                        null=True,
                    ),
                ),
                (
                    "warning_count",
                    models.IntegerField(
                        default=0, help_text="Number of times account has been flagged"
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_state",
                        to="accounts.customeraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=100, unique=True)),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash of IP address for privacy",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "is_flagged_suspicious",
                    models.BooleanField(
                        default=False, help_text="Flagged by concurrency enforcement"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
