# Generated by Django 5.0.1 on 2025-10-25 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("FREE", "FREE"),
                            ("PLUS", "PLUS"),
                            ("PRO", "PRO"),
                            ("ENTERPRISE", "ENTERPRISE"),
                        ],
                        help_text="Internal plan code (FREE, PLUS, PRO, ENTERPRISE)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Marketing label (e.g., 'Professional Plan')",
                        max_length=100,
                    ),
                ),
                (
                    "monthly_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in USD per month",
                        max_digits=10,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe Price ID (e.g., price_xxxxx)",
                        max_length=100,
                    ),
                ),
                (
                    "char_limit",
                    models.BigIntegerField(help_text="Monthly character limit"),
                ),
                (
                    "req_per_hour",
                    models.IntegerField(help_text="API requests allowed per hour"),
                ),
                (
                    "max_seats",
                    models.IntegerField(
                        help_text="Maximum team members (1 for FREE/PLUS, 5+ for PRO/ENTERPRISE)"
                    ),
                ),
                (
                    "max_concurrent_sessions",
                    models.IntegerField(
                        default=2, help_text="Max concurrent sessions per user"
                    ),
                ),
                (
                    "allow_team_members",
                    models.BooleanField(
                        default=False,
                        help_text="Whether plan allows inviting team members",
                    ),
                ),
                (
                    "priority_support",
                    models.BooleanField(
                        default=False, help_text="Dedicated support channel"
                    ),
                ),
                (
                    "sla",
                    models.BooleanField(
                        default=False, help_text="SLA guarantee (99.9% uptime, etc.)"
                    ),
                ),
            ],
            options={
                "ordering": ["monthly_price_usd"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                (
                    "is_trial",
                    models.BooleanField(
                        default=False, help_text="True if in trial period"
                    ),
                ),
                (
                    "is_canceled",
                    models.BooleanField(
                        default=False, help_text="True if subscription is canceled"
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="accounts.customeraccount",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
        ),
    ]
