# Generated by Django 5.0.1 on 2025-10-17 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("STARTER", "Starter"),
                            ("PRO", "Pro"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        help_text="Name of the billing plan",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly subscription price in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "character_limit",
                    models.IntegerField(
                        help_text="Maximum characters allowed per month"
                    ),
                ),
                (
                    "api_rate_limit_per_hour",
                    models.IntegerField(
                        help_text="Maximum API requests allowed per hour"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=dict,
                        help_text="Additional features included in this plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "ordering": ["monthly_price"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                        ],
                        default="active",
                        help_text="Current status of the subscription",
                        max_length=20,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        help_text="Start date of the current billing period"
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        help_text="End date of the current billing period"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when subscription was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when subscription was last updated",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Billing plan for this subscription",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="billing_sub_user_id_fe5b98_idx"
                    ),
                    models.Index(
                        fields=["status"], name="billing_sub_status_948046_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "characters_used",
                    models.IntegerField(
                        default=0,
                        help_text="Number of characters used in the current period",
                    ),
                ),
                (
                    "reset_date",
                    models.DateField(help_text="Date when the quota will be reset"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose quota is being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_quotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Quota",
                "verbose_name_plural": "Usage Quotas",
                "ordering": ["-reset_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "reset_date"],
                        name="billing_usa_user_id_77c8e2_idx",
                    )
                ],
                "unique_together": {("user", "reset_date")},
            },
        ),
    ]
