# Generated by Django 5.0.1 on 2025-10-25 00:35

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        default=api.models.generate_api_key,
                        help_text="The API key value",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this key (e.g., 'WordPress Plugin')",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this key is currently active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when key was created"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when key was last used",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this API key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["key"], name="api_apikey_key_5dc959_idx"),
                    models.Index(
                        fields=["user", "is_active"],
                        name="api_apikey_user_id_90f679_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="APIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        help_text="API endpoint that was called (e.g., '/api/v1/summarize/')",
                        max_length=100,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="HTTP method (POST, GET, etc.)", max_length=10
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(help_text="HTTP response status code"),
                ),
                (
                    "character_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of characters processed in this request",
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when request was made",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if request failed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Request Log",
                "verbose_name_plural": "API Request Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="api_apirequ_user_id_4fe6e8_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "timestamp"],
                        name="api_apirequ_endpoin_e3ca03_idx",
                    ),
                    models.Index(
                        fields=["status_code", "timestamp"],
                        name="api_apirequ_status__ad2545_idx",
                    ),
                ],
            },
        ),
    ]
